name: Video Processing & Upload Workflow

on:
  workflow_dispatch:
    inputs:
      tolerance:
        description: 'Chroma Key Tolerance (0-255)'
        required: true
        default: '50'
        type: string
      apply_channel_shift:
        description: 'Apply Channel Shift Effect?'
        required: true
        type: boolean
        default: false
      apply_edge:
        description: 'Apply Edge Detection Effect?'
        required: true
        type: boolean
        default: false
      apply_hue_cycle:
        description: 'Apply Hue Cycle Effect?'
        required: true
        type: boolean
        default: false
      shift_intensity:
        description: 'Intensity for Channel Shift effect (e.g., 10)'
        required: true
        default: '10'
        type: string

env:
  MP4_VIDEO_NAME: 'final_video.mp4'
  FINAL_VIDEO_NAME: 'final_video.mov'

jobs:
  process_and_upload:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('random_chroma.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install opencv-python numpy

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download input videos
        run: |
          wget https://github.com/Emon2358/4949downloader/raw/main/downloads/sm9875066.mp4 -O video1.mp4
          wget https://github.com/Emon2358/4949downloader/raw/main/downloads/sm39403653.mp4 -O video2.mp4

      - name: Run video processing script
        run: |
          python random_chroma.py \
            --tolerance ${{ github.event.inputs.tolerance }} \
            --apply-channel-shift ${{ github.event.inputs.apply_channel_shift }} \
            --apply-edge ${{ github.event.inputs.apply_edge }} \
            --apply-hue-cycle ${{ github.event.inputs.apply_hue_cycle }} \
            --shift-intensity ${{ github.event.inputs.shift_intensity }}

      - name: Convert MP4 to MOV (Fast)
        run: |
          ffmpeg -i ${{ env.MP4_VIDEO_NAME }} -preset ultrafast ${{ env.FINAL_VIDEO_NAME }}

      - name: Create Release and Upload Video
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FINAL_VIDEO_NAME }}
          tag_name: video-${{ github.run_id }}
          name: "Video from workflow #${{ github.run_id }}"
          body: |
            Video generated with the following parameters:
            - Tolerance: ${{ github.event.inputs.tolerance }}
            - Channel Shift: ${{ github.event.inputs.apply_channel_shift }}
            - Edge Detection: ${{ github.event.inputs.apply_edge }}
            - Hue Cycle: ${{ github.event.inputs.apply_hue_cycle }}
            - Shift Intensity: ${{ github.event.inputs.shift_intensity }}

      - name: Upload final video as artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: ${{ env.FINAL_VIDEO_NAME }}
